ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER warehouse compute_wh suspend;
ALTER warehouse compute_wh resume;



CREATE OR REPLACE TRANSIENT DATABASE ORDERS;

CREATE OR REPLACE SCHEMA TPCH_SF100;

CREATE OR REPLACE TABLE TPCH_SF100.ORDERS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS;

SELECT * FROM ORDERS LIMIT 100;

SELECT YEAR(O_ORDERDATE) AS YEAR,
MAX(O_COMMENT) AS MAX_COMMENT,
MIN(O_COMMENT) AS MIN_COMMENT,
MAX(O_CLERK) AS MAX_CLERK,
MIN(O_CLERK) AS MIN_CLERK
FROM ORDERS.TPCH_SF100.ORDERS
GROUP BY YEAR(O_ORDERDATE)
ORDER BY YEAR(O_ORDERDATE);


CREATE OR REPLACE MATERIALIZED VIEW ORDERS_MV
AS
SELECT YEAR(O_ORDERDATE) AS YEAR,
MAX(O_COMMENT) AS MAX_COMMENT,
MIN(O_COMMENT) AS MIN_COMMENT,
MAX(O_CLERK) AS MAX_CLERK,
MIN(O_CLERK) AS MIN_CLERK
FROM ORDERS.TPCH_SF100.ORDERS
GROUP BY YEAR(O_ORDERDATE);

SHOW MATERIALIZED VIEWS;

SELECT * FROM ORDERS_MV
ORDER BY YEAR;


--updating orders table
UPDATE ORDERS 
SET O_CLERK = 'Clerk#12345'
WHERE O_ORDERDATE = '1992-01-01';


-- behind by column in show materialized view tells how back our view is when compared to data in actual table
SHOW MATERIALIZED VIEWS;

DROP DATABASE ORDERS;