
//Creating a table in snowflake with Database name DATAWAREHOUSE_DB, schema with name Apple_data_analysis and table with name IPHONE_DATA

create or replace TABLE DATAWAREHOUSE_DB.APPLE_DATA_ANALYSIS.IPHONE_DATA (
	PRODUCT_NAME VARCHAR(16777216),
	PRODUCT_URL VARCHAR(16777216),
	BRAND VARCHAR(16777216),
	SALES_PRICE NUMBER(38,0),
	MRP NUMBER(38,0),
	DISCOUNT_PERCENTAGE NUMBER(38,0),
	NUMBER_OF_RATINGS NUMBER(38,0),
    NUMBER_OF_REVIEWS NUMBER(38,0),
	UPC VARCHAR(16777216),
	STAR_RATING FLOAT,
	RAM VARCHAR(16777216)
)COMMENT='this table contains information about iPhone data'
;