SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS;


CREATE TABLE OUR_FIRST_DB.PUBLIC.CUSTOMERS_CLONE
CLONE OUR_FIRST_DB.PUBLIC.CUSTOMERS;

SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS_CLONE;

UPDATE OUR_FIRST_DB.PUBLIC.CUSTOMERS_CLONE
SET LAST_NAME = NULL;

SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS;

//CLONING TEMPORARY TABLE
CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.TEMP_TABLE(
id int
);

CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.TEMP_TABLE_CLONE 
CLONE OUR_FIRST_DB.PUBLIC.TEMP_TABLE
;

//CLONING SCHEMA
CREATE OR REPLACE TRANSIENT SCHEMA OUR_FIRST_DB.COPIED_SCHEMA
CLONE OUR_FIRST_DB.PUBLIC;

SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.CUSTOMERS;

//CLONING DATABASE
CREATE TRANSIENT DATABASE OUR_FIRST_DB_COPY
CLONE OUR_FIRST_DB;


DROP DATABASE OUR_FIRST_DB_COPY;
DROP SCHEMA OUR_FIRST_DB.COPIED_SCHEMA;
